kind: pipeline
name: default



steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch origin

- name: build
  image: quay.io/vlad/bfc
  environment:
    GIT_USER: vtemian
    GIT_EMAIL: vladtemian@gmail.com
    GIT_PASSWORD:
      from_secret: GIT_PASSWORD
  commands:
  - yarn
  - npm run build
  - ./bin/publish.sh
  when:
    branch:
    - content
